name: Render - Build and run Tests

on:
  [push, pull_request]

jobs:
  render_build_and_run_tests:
    name: Render - Build and run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'ubuntu-24.04-arm', 'macos-15-intel', 'macos-latest', 'windows-latest']
        render_backend: ['bgfx', 'opengl2']
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        cache: 'true'
        version: '6.8.2'
    - name: Install dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install cmake ninja-build libtbb-dev catch2
        sudo apt-get install freeglut3-dev libgl1-mesa-dev libxi-dev libxinerama-dev libxcursor-dev libxrandr-dev libglfw3-dev
    - name: Install dependencies
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install catch2 glfw
    - name: Install dependencies
      if: runner.os == 'Windows'
      run: |
        winget install Ccache.Ccache Ninja-build.Ninja --accept-source-agreements --accept-package-agreements
    - name: Ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: render-${{ matrix.os }}-${{matrix.render_backend}}-${{ github.ref_name }}
    - name: Build
      shell: bash
      run: |
        mkdir build
        cmake -B build --preset=vclib-render-${{matrix.render_backend}}-ci \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        cmake --build build --parallel
    # - name: Run Tests
    #   shell: bash
    #   run: |
    #     cd build
    #     ctest --verbose
